Repository TeonaRusu/TI-Project, pull requests merged in 2018-04, with the labels that each got.

#47 Add jsp files
  TuxyDriveCore/.classpath
  TuxyDriveCore/.project
  TuxyDriveCore/.settings/org.eclipse.jdt.core.prefs
  TuxyDriveCore/.settings/org.eclipse.wst.common.component
  TuxyDriveCore/.settings/org.eclipse.wst.common.project.facet.core.xml
  TuxyDriveCore/src/META-INF/MANIFEST.MF
  TuxyDriveSSW/.classpath
  TuxyDriveSSW/.project
  TuxyDriveSSW/.settings/org.eclipse.wst.common.component
  TuxyDriveSW/WebContent/api/login.jsp
  TuxyDriveSW/WebContent/api/register.jsp
  TuxyDriveSW/WebContent/css/style.css
  TuxyDriveSW/WebContent/home.jsp
  TuxyDriveSW/WebContent/images/logo.png
  TuxyDriveSW/WebContent/index.jsp
Labels: critical, enhancement

#48 add ssw
  TuxyDriveCore/src/data/UserLogin.java
  TuxyDriveSSW/src/manager/DBManager.java
  TuxyDriveSSW/src/servicii/web/LoginService.java
Labels: critical, enhancement

#49 Add servlet server
  TuxyDriveSW/.project
  TuxyDriveSW/src/servlet/LoginServlet.java
Labels: critical, enhancement, help wanted

#56 Add js script; update jsp files
  TuxyDriveCore/.classpath
  TuxyDriveCore/lib/jackson-annotations-2.9.5.jar
  TuxyDriveSSW/.classpath
  TuxyDriveSSW/lib/commons-codec-1.11-javadoc.jar
  TuxyDriveSSW/lib/commons-codec-1.11-sources.jar
  TuxyDriveSSW/lib/commons-codec-1.11-test-sources.jar
  TuxyDriveSSW/lib/commons-codec-1.11-tests.jar
  TuxyDriveSSW/lib/commons-codec-1.11.jar
  TuxyDriveSSW/lib/jackson-annotations-2.9.5.jar
  TuxyDriveSSW/lib/jackson-core-2.9.5.jar
  TuxyDriveSSW/lib/jackson-databind-2.9.5.jar
  TuxyDriveSSW/lib/javax.ws.rs.jar
  TuxyDriveSW/WebContent/api/login.jsp
  TuxyDriveSW/WebContent/api/logout.jsp
  TuxyDriveSW/WebContent/api/register.jsp
  TuxyDriveSW/WebContent/css/style.css
  TuxyDriveSW/WebContent/home.jsp
  TuxyDriveSW/WebContent/images/index-img.png
  TuxyDriveSW/WebContent/index.jsp
  TuxyDriveSW/WebContent/js/myscript.js
  TuxyDriveSW/src/servlet/LoginServlet.java
Labels: enhancement

#57 Update documentation
  Documentation.md
Labels: documentation, help wanted

#68 Documentation part 2
  Documentation.md
Labels: documentation, major
