Repository TeonaRusu/TI-Project, pull requests merged in 2018-05, with the labels that each got.

#74 added servlet for register
  TuxyDriveSW/WebContent/api/register.jsp
  TuxyDriveSW/WebContent/home.jsp
  TuxyDriveSW/WebContent/js/myscript.js
  TuxyDriveSW/WebContent/js/script.js
  TuxyDriveSW/src/servlet/LoginServlet.java
  TuxyDriveSW/src/servlet/RegisterServlet.java
Labels: critical, enhancement

#81 register_service
  TuxyDriveCore/src/data/User.java
  TuxyDriveSSW/src/manager/DBManager.java
  TuxyDriveSSW/src/servicii/web/RegisterService.java
  TuxyDriveSW/WebContent/register.jsp
  TuxyDriveSW/src/servlet/LoginServlet.java
  TuxyDriveSW/src/servlet/RegisterServlet.java
Labels: critical

#89 add review for lider
  Documentation.md
  TuxyDriveSW/WebContent/css/style2.css
  TuxyDriveSW/WebContent/js/script.js
Labels: documentation
